Add README.md
game1n/t8-cms pull request #16
Opened 2022-10-01 17:27 UTC by clairecharles

## Fixes issue
Create well documented README.md file #4

2022-10-01 17:42 UTC, ps-89 commented on README.md
> +npm install
We use yarn as package manager, so this would be replaced with `yarn install`

2022-10-01 18:22 UTC, kishankr7979 requested changes

2022-10-01 18:22 UTC, kishankr7979 commented on README.md
> +npm run dev
since we are using yarn, it should be yarn start

2022-10-01 19:11 UTC, kishankr7979 requested changes

2022-10-01 19:11 UTC, kishankr7979 commented on README.md
> +Yarn install
`yarn install`

2022-10-01 19:11 UTC, kishankr7979 commented on README.md
> +Yarn start
`yarn start`

2022-10-02 04:06 UTC, ps-89 commented
Thanks for contributing @clairecharles. I'm merging the PR.

2022-10-02 04:07 UTC, merged